name: Ellie Website

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: ğŸ‘·â€â™‚ï¸ Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.16]
    env:
      CI: true

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          persist-credentials: false

      - name: ğŸ‘¾ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ‘€ Cache Node Modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: ğŸ›° Install dependencies
        # if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          yarn --frozen-lockfile --production=false

      - name: ğŸ‘·â€â™€ï¸ Build
        run: |
          yarn build

      - name: ğŸ° Deploy to Bunny
        uses: own3d/bunny-action@main
        env:
          BUNNY_STORAGE_USERNAME: ellie-website
          BUNNY_STORAGE_PASSWORD: 124768e3-6266-4c15-a6fa026401b4-b799-487b
          BUNNY_PULL_ZONE_ID: 212288
        with:
          args: deploy --dir=dist

      - name: ğŸ’¬ Report
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ğŸš€ Deployed Ellie website from main

      - name: ğŸ’¬ Report Failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ğŸ’© Ellie website deploy failed
